configs:
  # not used currently - for test purposes
  test-schema.sql:
    content: |
      create schema iceberg.test;
      create table iceberg.test.customer as select * from tpch.tiny.customer;
      create table iceberg.test.lineitem as select * from tpch.tiny.lineitem;
      create table iceberg.test.nation as select * from tpch.tiny.nation;
      create table iceberg.test.orders as select * from tpch.tiny.orders;
      create table iceberg.test.part as select * from tpch.tiny.part;
      create table iceberg.test.partsupp as select * from tpch.tiny.partsupp;
      create table iceberg.test.region as select * from tpch.tiny.region;
      create table iceberg.test.supplier as select * from tpch.tiny.supplier;

  iceberg.properties:
    content: |
      connector.name=iceberg
      iceberg.catalog.type=rest
      iceberg.rest-catalog.uri=http://rest:8181
      iceberg.rest-catalog.warehouse=s3://${S3_BUCKET_NAME}/
      iceberg.file-format=PARQUET
      
      # S3 configuration
      # see also https://github.com/trinodb/trino/pull/16557
      fs.native-s3.enabled=true
      s3.endpoint=http://minio:9000
      s3.path-style-access=true
      s3.aws-access-key=${AWS_ACCESS_KEY_ID}
      s3.aws-secret-key=${AWS_SECRET_ACCESS_KEY}
      s3.region=${AWS_REGION}

services:
  rest:
    image: ${ICEBERG_REST_IMAGE:-tabulario/iceberg-rest:1.6.0}
    container_name: iceberg-rest
    networks:
      iceberg_network:
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8181:8181
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      CATALOG_WAREHOUSE: s3://${S3_BUCKET_NAME}/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_PATH__STYLE__ACCESS: true # to avoid creating alias for minio in network: warehouse.minio
      CATALOG_URI: jdbc:postgresql://postgres/iceberg_catalog
      CATALOG_JDBC_USER: ${POSTGRES_USER:-trino}
      CATALOG_JDBC_PASSWORD: ${POSTGRES_PASSWORD:-password}

  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: iceberg_catalog
      POSTGRES_HOST_AUTH_METHOD: md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d iceberg_catalog"]
      interval: 5s
      timeout: 5s
      retries: 5