services:
  minio:
    image: ${MINIO_IMAGE:-minio/minio:RELEASE.2025-04-22T22-12-26Z}
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      MINIO_DOMAIN: minio
    networks:
      iceberg_network:
    volumes:
      - minio_data:/data
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  mc:
    depends_on:
      - minio
    image: ${MC_IMAGE:-minio/mc}
    container_name: mc
    networks:
      iceberg_network:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    entrypoint: >
      /bin/sh -c "
          until (/usr/bin/mc alias set minio http://minio:9000 $${AWS_ACCESS_KEY_ID} $${AWS_SECRET_ACCESS_KEY}) do echo '...waiting...' && sleep 1; done;
          /usr/bin/mc mb minio/warehouse || true;
          /usr/bin/mc anonymous set public minio/warehouse;
          tail -f /dev/null
      "

networks:
  iceberg_network:

volumes:
  minio_data: